"use client";

import { ArrowRight, Check, MessageSquareText, Users } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { KOCAELI_DISTRICTS, KOCAELI_PARKS } from "../data/kocaeliParks";
import { recordsApi } from "../services/api";
import { PublicFooter, PublicHeader } from "./PublicChrome";

export default function ContactPage(){
  type ParkRecord={id:number;name:string;district:string;neighborhood:string};
  const [district,setDistrict]=useState("");const [sent,setSent]=useState(false);const [error,setError]=useState("");const [sending,setSending]=useState(false);
  const [allParks,setAllParks]=useState<ParkRecord[]>([]);
  useEffect(()=>{void(async()=>{try{let rows=await recordsApi.list<ParkRecord>("parks");if(rows.length===0)rows=await recordsApi.bootstrap("parks",KOCAELI_PARKS.map((park,index)=>({id:index+1,...park,capacity:500,status:"Aktif",score:0})));setAllParks(rows)}catch(exception){setError(exception instanceof Error?exception.message:"Parklar yüklenemedi.")}})()},[]);
  const parks=useMemo(()=>allParks.filter(park=>park.district===district),[allParks,district]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);setSending(true);setError("");try{await recordsApi.create("reports",{title:String(data.get("subject")),park:String(data.get("park")),citizen:String(data.get("name")||"İsimsiz Vatandaş"),category:String(data.get("category")),date:new Date().toLocaleDateString("tr-TR"),district:String(data.get("district")),description:String(data.get("message")),status:"Bekliyor"});form.reset();setDistrict("");setSent(true)}catch(exception){setError(exception instanceof Error?exception.message:"Mesaj gönderilemedi.")}finally{setSending(false)}};
  return <main className="public-page"><PublicHeader/><section className="inner-hero"><MessageSquareText/><span>İLETİŞİM</span><h1>Belediyeye doğrudan yazın</h1><p>Parklarla ilgili sorun, görüş ve önerilerinizi üyelik oluşturmadan iletin.</p></section><section className="contact-section standalone"><div className="contact-copy"><span>VATANDAŞ İLETİŞİMİ</span><h2>Mesajınız doğru saha ekibine ulaşsın.</h2><p>İlçe ve park seçiminize göre bildiriminiz yetkili paneline düşer ve ayrıntılı metniyle görüntülenir.</p><div className="contact-promise"><Check/><div><strong>Giriş gerekmez</strong><span>Form ücretsiz ve herkese açıktır.</span></div></div><div className="contact-promise"><Users/><div><strong>Takip edilebilir kayıt</strong><span>Bildirim belediye operatörünün ekranına eklenir.</span></div></div></div><form className="citizen-form" onSubmit={submit}><div className="form-title"><MessageSquareText/><div><strong>Vatandaş mesajı</strong><span>Tüm alanları ayrıntılı doldurabilirsiniz.</span></div></div><div className="public-form-grid"><label>Adınız <span>(isteğe bağlı)</span><input name="name"/></label><label>İlçe<select name="district" required value={district} onChange={e=>setDistrict(e.target.value)}><option value="" disabled>İlçe seçin</option>{KOCAELI_DISTRICTS.map(d=><option key={d}>{d}</option>)}</select></label><label>Park<select name="park" required defaultValue="" disabled={!district} key={district}><option value="" disabled>{district?"Park seçin":"Önce ilçe seçin"}</option>{parks.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Kategori<select name="category" required defaultValue=""><option value="" disabled>Kategori seçin</option><option>Arıza</option><option>Temizlik</option><option>Ekipman</option><option>Aydınlatma</option><option>Erişilebilirlik</option><option>Öneri</option></select></label><label className="wide">Konu<input name="subject" required/></label><label className="wide">Mesajınız<textarea name="message" required rows={5}/></label></div><button className="form-submit" disabled={sending}>{sending?"Gönderiliyor...":"Mesajı belediyeye ilet"} <ArrowRight/></button>{error&&<div className="form-error">{error}</div>}{sent&&<div className="form-success"><Check/><span><strong>Mesajınız alındı.</strong> Yetkili ekip bilgilendirildi.</span></div>}</form></section><PublicFooter/></main>
}
