CREATE DATABASE IF NOT EXISTS smartpark_plus CHARACTER SET utf8mb4 COLLATE utf8mb4_turkish_ci;
USE smartpark_plus;

CREATE TABLE roles (id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(40) NOT NULL UNIQUE, description VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role_id TINYINT UNSIGNED NOT NULL, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, phone VARCHAR(30), status ENUM('active','passive') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id));
CREATE TABLE districts (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE neighborhoods (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, district_id INT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL, UNIQUE KEY uq_neighborhood (district_id,name), CONSTRAINT fk_neighborhood_district FOREIGN KEY (district_id) REFERENCES districts(id));
CREATE TABLE parks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, district_id INT UNSIGNED NOT NULL, neighborhood_id INT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL, description TEXT, latitude DECIMAL(10,7) NOT NULL, longitude DECIMAL(10,7) NOT NULL, capacity INT UNSIGNED DEFAULT 0, density TINYINT UNSIGNED DEFAULT 0, opening_time TIME, closing_time TIME, status ENUM('active','maintenance','closed') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_park_district FOREIGN KEY (district_id) REFERENCES districts(id), CONSTRAINT fk_park_neighborhood FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id));
CREATE TABLE park_images (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, park_id BIGINT UNSIGNED NOT NULL, file_path VARCHAR(255) NOT NULL, is_cover BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_image_park FOREIGN KEY (park_id) REFERENCES parks(id) ON DELETE CASCADE);
CREATE TABLE equipment_types (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, maintenance_interval_days SMALLINT UNSIGNED NOT NULL DEFAULT 90);
CREATE TABLE equipment (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, park_id BIGINT UNSIGNED NOT NULL, type_id INT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL, condition_status ENUM('good','fair','poor','out_of_service') DEFAULT 'good', fault_status BOOLEAN DEFAULT FALSE, last_maintenance_at DATE, next_maintenance_at DATE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_equipment_park FOREIGN KEY (park_id) REFERENCES parks(id), CONSTRAINT fk_equipment_type FOREIGN KEY (type_id) REFERENCES equipment_types(id));
CREATE TABLE maintenance_records (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, park_id BIGINT UNSIGNED NOT NULL, equipment_id BIGINT UNSIGNED NULL, assigned_user_id BIGINT UNSIGNED NULL, maintenance_type ENUM('watering','mowing','cleaning','painting','pruning','equipment_repair','electrical') NOT NULL, scheduled_at DATETIME NOT NULL, completed_at DATETIME NULL, status ENUM('pending','assigned','in_progress','completed','cancelled') DEFAULT 'pending', notes TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_maintenance_park FOREIGN KEY (park_id) REFERENCES parks(id), CONSTRAINT fk_maintenance_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(id), CONSTRAINT fk_maintenance_user FOREIGN KEY (assigned_user_id) REFERENCES users(id));
CREATE TABLE tasks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, park_id BIGINT UNSIGNED NOT NULL, assigned_user_id BIGINT UNSIGNED NOT NULL, created_by BIGINT UNSIGNED NOT NULL, maintenance_id BIGINT UNSIGNED NULL, title VARCHAR(180) NOT NULL, description TEXT, start_at DATETIME, due_at DATETIME NOT NULL, completed_at DATETIME, status ENUM('pending','assigned','in_progress','completed','cancelled') DEFAULT 'assigned', completion_note TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_task_park FOREIGN KEY (park_id) REFERENCES parks(id), CONSTRAINT fk_task_assignee FOREIGN KEY (assigned_user_id) REFERENCES users(id), CONSTRAINT fk_task_creator FOREIGN KEY (created_by) REFERENCES users(id), CONSTRAINT fk_task_maintenance FOREIGN KEY (maintenance_id) REFERENCES maintenance_records(id));
CREATE TABLE citizen_reports (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, citizen_id BIGINT UNSIGNED NOT NULL, park_id BIGINT UNSIGNED NOT NULL, category VARCHAR(80) NOT NULL, description TEXT NOT NULL, latitude DECIMAL(10,7), longitude DECIMAL(10,7), image_path VARCHAR(255), status ENUM('waiting','reviewing','in_progress','completed','rejected') DEFAULT 'waiting', rejection_reason VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_report_citizen FOREIGN KEY (citizen_id) REFERENCES users(id), CONSTRAINT fk_report_park FOREIGN KEY (park_id) REFERENCES parks(id));
CREATE TABLE report_status_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, report_id BIGINT UNSIGNED NOT NULL, changed_by BIGINT UNSIGNED NOT NULL, old_status VARCHAR(30), new_status VARCHAR(30) NOT NULL, note VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_history_report FOREIGN KEY (report_id) REFERENCES citizen_reports(id) ON DELETE CASCADE, CONSTRAINT fk_history_user FOREIGN KEY (changed_by) REFERENCES users(id));
CREATE TABLE events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, park_id BIGINT UNSIGNED NOT NULL, created_by BIGINT UNSIGNED NOT NULL, title VARCHAR(180) NOT NULL, event_type VARCHAR(80) NOT NULL, description TEXT, start_at DATETIME NOT NULL, end_at DATETIME NOT NULL, capacity INT UNSIGNED, status ENUM('draft','published','cancelled','completed') DEFAULT 'draft', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_event_park FOREIGN KEY (park_id) REFERENCES parks(id), CONSTRAINT fk_event_creator FOREIGN KEY (created_by) REFERENCES users(id));
CREATE TABLE notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, type VARCHAR(60) NOT NULL, channel ENUM('dashboard','email','push') DEFAULT 'dashboard', title VARCHAR(180) NOT NULL, message TEXT NOT NULL, read_at DATETIME, delivery_status ENUM('pending','sent','failed') DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX ix_notification_user_read (user_id,read_at), CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE maintenance_priority_scores (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, park_id BIGINT UNSIGNED NOT NULL, score DECIMAL(5,2) NOT NULL, component_values JSON NOT NULL, calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX ix_priority_score (score), CONSTRAINT fk_score_park FOREIGN KEY (park_id) REFERENCES parks(id) ON DELETE CASCADE);

CREATE TABLE module_records (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    module_key VARCHAR(40) NOT NULL,
    payload JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX ix_module_records_key (module_key),
    INDEX ix_module_records_updated (updated_at)
);
